[package]
name = "luban-preconfer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true }
alloy-contract = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-core = { workspace = true }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-rlp = { version = "0.3.4", features = ["derive"] }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-rpc-types-beacon = { workspace = true }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-sol-types = { version = "0.7.4" }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
eyre = { workspace = true }
jsonrpsee = { workspace = true }
luban-primitives = { workspace = true }
parking_lot = { workspace = true }
reqwest = "0.12.4"
serde = { workspace = true }
serde_json ={ workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client", rev = "83f62f6e0174c65a65fd35a17e30c12cd923c0b8" }
cb-crypto = { git = "https://github.com/Commit-Boost/commit-boost-client", rev = "83f62f6e0174c65a65fd35a17e30c12cd923c0b8" }

[lib]
