[workspace.package]
name = "preconfer"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["bin", "crates/cli", "crates/preconfer", "crates/primitives", "tests"]
resolver = "2"

[workspace.dependencies]
luban-preconfer = { path = "crates/preconfer" }
luban-cli = { path = "crates/cli" }
luban-primitives = { path = "crates/primitives" }
luban-integration-tests = { path = "tests" }

jsonrpsee = { version = "0.22.4", features = ["server", "http-client", "ws-client", "macros"] }
alloy-core = { version = "0.7.2", features = ["serde", "rlp", "sol-types"] }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
alloy-rpc-types-beacon = { git = "https://github.com/alloy-rs/alloy", rev = "975b849ab11a1bbc7285f46dcb0b99b7df7e438b" }
eyre = { version = "0.6" }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16", features = ["full"] }
thiserror = { version = "1" }
parking_lot = "0.12"
futures = "0.3.30"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
