[package]
name = "taiyi-cmd"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-contract = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
blst = { workspace = true }

clap = { workspace = true }
ethereum-consensus = { workspace = true }
eyre = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true }
lighthouse_eth2_keystore = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
taiyi-common = { workspace = true }
taiyi-preconfer = { workspace = true }
tiny-bip39 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
