[package]
name = "taiyi-underwriter-monitor"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

clap = { workspace = true }
eyre = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
reqwest-eventsource = "0.6"
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
taiyi-primitives = { workspace = true }
taiyi-underwriter = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }


[dev-dependencies]
