[package]
name = "taiyi-underwriter-monitor"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
reqwest-eventsource = "0.6"
serde_json = { workspace = true }
sqlx = { workspace = true }
taiyi-primitives = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
