[package]
name = "taiyi-zkvm-types"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
serde = { workspace = true }
ssz_rs = { workspace = true }
thiserror = { workspace = true }
taiyi-primitives = { workspace = true }
