[package]
name = "taiyi-cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
taiyi-cmd = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tree_hash = { workspace = true }

[dev-dependencies]
