[package]
name = "taiyi-examples"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-provider = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
eyre = { workspace = true }
reqwest = "0.12"
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v0.2.0-beta.6" }
serde_json = "1"
taiyi-primitives = { workspace = true }
tokio = { workspace = true }

[lib]

[[example]]
name = "submit-preconf-request"
path = "src/submit-preconf-request.rs"

[package.metadata.cargo-udeps.ignore]
normal = ["alloy-provider", "alloy-signer", "alloy-signer-local", "eyre", "taiyi-primitives", "reqwest", "reth-primitives", "secp256k1", "serde", "serde_json", "tokio"]
