[package]
name = "sp1-ifp-script"
version = "0.1.0"
edition = "2021"
default-run = "sp1-ifp-script"
publish = false

[dependencies]
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }

[[bin]]
name = "sp1-ifp-script"
path = "src/main.rs"
