[package]
name = "taiyi-beacon-client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-rpc-types-engine = { workspace = true }
blst = { workspace = true }
const-hex = "1.13.2"
eyre = { workspace = true }
reqwest = { version = "0.11.27", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
hex = { workspace = true }
beacon-api-client = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[lib]
path = "src/lib.rs"