[package]
name = "taiyi"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "taiyi"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
taiyi-cmd = { workspace = true }
tokio = { workspace = true }
