[package]
name = "taiyi-boost"
version = "0.1.0"
edition = "2021"

[dependencies]
commit-boost = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
