[package]
name = "taiyi-boost"
version = { workspace = true }
edition = "2021"

[dependencies]
taiyi-beacon-client = { workspace = true }
taiyi-cmd = { workspace = true }
taiyi-primitives = { workspace = true }

alloy = { workspace = true }
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }
alloy-transport-http = { workspace = true, features = ["jwt-auth"] }

async-trait = { workspace = true }
axum = { workspace = true }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
cb-common = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http-body-util = { workspace = true }
lazy_static = { workspace = true }
parking_lot = { workspace = true }
prometheus = { workspace = true }
regex = "1.11.2"
reqwest = { workspace = true, features = ["json"] }
scc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ssz_rs = { workspace = true }
ssz_types = { workspace = true }
taiyi-crypto = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tracing = { workspace = true }
tree_hash = { workspace = true }
tree_hash_derive = { workspace = true }

reqwest-eventsource = "0.6"

[dev-dependencies]
# alloy-node-bindings = { workspace = true }
ethereum_ssz = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
