name: e2e tests

on:
  workflow_call:
  push:
    branches:
      - dev
  pull_request:

env:
  ENCLAVE_NAME: luban

jobs:
  build-docker-image:
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get latest tag
        id: get_tag
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Pull latest image
        run: docker pull ${{ vars.DOCKER_REPO_NAME }}/taiyi:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ vars.DOCKER_REPO_NAME }}/taiyi:latest
            ${{ vars.DOCKER_REPO_NAME }}/taiyi:${{ env.TAG }}

  e2e:
    name: Run e2e tests
    runs-on: ubuntu-latest-m
    needs: build-docker-image
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version v4.0.1
          ~/.sp1/bin/cargo-prove prove --version
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - name: Run kurtosis devnet
        run: |
          make e2e-network
      - name: Pre setup taiyi
        run: |
          make e2e-setup
      - name: Run e2e tests
        run: |
          make e2e-test
  e2e-fraud:
    name: Run e2e fraud tests 
    runs-on: ubuntu-latest-m
    needs: build-docker-image
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version v4.0.1
          ~/.sp1/bin/cargo-prove prove --version
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - name: Run kurtosis devnet
        run: |
          make e2e-network
      - name: Pre setup taiyi
        run: |
          make e2e-setup
      - name: Run e2e fraud tests
        run: |
          make e2e-fraud-test